blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/rgleichman/map-backend/discussions/categories/q-a
    about: For general questions, ideas, or help, please use GitHub Discussions Q&A.
